version: "3.9"

services:
  react:
    build: ./client
    container_name: meet-and-cheese-client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND="http://localhost:${API_PORT}/api"
    depends_on:
      - api

  api:
    build: ./server
    container_name: meet-and-cheese-server
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - PORT=${API_PORT}
